### ISSUE TITLE
Broken examples?

### ISSUE THREAD

**Issue by joerno** [troch/angular-multi-step-form#4]
Hello,

I get some JavaScript errors and the examples are not working correctly. The HTML and JavaScript-Tabs are empty (I use chrome).

TypeError: Cannot read property 'configure' of undefined
    at Object.$get (http://pc035860.github.io/angular-highlightjs/angular-highlightjs.min.js:6:518)
    at Object.e [as invoke](https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:36:315)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:38:110
    at d (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:36:13)
    at Object.e [as invoke](https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:36:283)
    at x.instance (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:76:79)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:59:85
    at q (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:7:428)
    at M (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:59:69)
    at g (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js:51:409) <div class="tab-pane ng-scope" ng-repeat="tab in tabs" ng-class="{active: tab.active}" tab-content-transclude="tab">

**Comment by troch** [comment]
Hi @joerno, thanks for reporting this. It has been fixed.
